<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>E_Commerce.Infrastructure_01</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.28" />
    <PackageReference Include="StackExchange.Redis" Version="3.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\E-Commerce-Domain-01\E-Commerce.Domain.csproj" />
    <ProjectReference Include="..\E-Commerce.Application-01\E-Commerce.Application.csproj" />
  </ItemGroup>

</Project>
